/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include"dataProgress.h"
/* Header for class com_psf_sapt_wifiService_DataProgress */

#ifndef _Included_com_psf_sapt_wifiService_DataProgress
#define _Included_com_psf_sapt_wifiService_DataProgress
#ifdef __cplusplus
extern "C" {
#endif

#define FRAMELENGTH 20
	dataProgress *mdata;
	bool has_init=false;
/*
 * Class:     com_psf_sapt_wifiService_DataProgress
 * Method:    getId
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_psf_sapt_wifiService_DataProgress_getId
  (JNIEnv *, jobject);

/*
 * Class:     com_psf_sapt_wifiService_DataProgress
 * Method:    getPureIDs
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_psf_sapt_wifiService_DataProgress_getPureIDs
  (JNIEnv *, jobject);

/*
 * Class:     com_psf_sapt_wifiService_DataProgress
 * Method:    getFrame
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_psf_sapt_wifiService_DataProgress_getFrame
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_psf_sapt_wifiService_DataProgress
 * Method:    setFrames
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_psf_sapt_wifiService_DataProgress_setFrames
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_psf_sapt_wifiService_DataProgress
 * Method:    setAllowSetNewData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_psf_sapt_wifiService_DataProgress_setAllowSetNewData
  (JNIEnv *, jobject);

/*
 * Class:     com_psf_sapt_wifiService_DataProgress
 * Method:    getID
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_psf_sapt_wifiService_DataProgress_getID
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_psf_sapt_wifiService_DataProgress
 * Method:    getLcuTempNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_psf_sapt_wifiService_DataProgress_getLcuTempNum
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_psf_sapt_wifiService_DataProgress
 * Method:    getFrameData
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_psf_sapt_wifiService_DataProgress_getFrameData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_psf_sapt_wifiService_DataProgress
 * Method:    getFrameFloatData
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_psf_sapt_wifiService_DataProgress_getFrameFloatData
  (JNIEnv *, jobject, jint);

JNIEXPORT void JNICALL Java_com_psf_sapt_wifiService_DataProgress_end
(JNIEnv *, jobject);



void init();
void end();

#ifdef __cplusplus
}
#endif
#endif
